### PR TITLE
Add support for PostgreSQL

### PR DESCRIPTION
**Pull request by Rahel-A**
- Pass POSTGRESQL_PASSWORD environment variable to Database Manager to open PostgreSQL.
- Install the required prerequisites for PostgreSQL in the Docker container.

Also see PR #260 for previous comments on this feature...

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Sorry, but for some reason this branch still has the two previous issues:

- `POSTGRES_PW` is not a config variable
- `str or None` is used as type hint

Could it be that you pushed the wrong branch?

**Comment by Rahel-A** [comment]
> Sorry, but for some reason this branch still has the two previous issues:
> 
>     * `POSTGRES_PW` is not a config variable
> 
>     * `str or None` is used as type hint
> 
> 
> Could it be that you pushed the wrong branch?

I'm confused, let's resync...

I'm using POSTGRES_PASSWORD instead of POSTGRES_PW to match the environment variable name with PostgreSQL. The gramps-webapi can read POSTGRES_PASSWORD env var as set through (docker) environment:
https://github.com/gramps-project/gramps-webapi/blob/c6a121221982db015919c70ffa37fb061fa737ec/gramps_webapi/app.py#L77
Are you asking me to add another method for gramps-webapi to read POSTGRES_PASSWORD (through some other configuration)?

I tried `password: Optional[str] = None` as your comment suggested but that didn't change any test case failures, instead I found that setting the type to be either str or None makes the test cases pass:
https://github.com/gramps-project/gramps-webapi/blob/c6a121221982db015919c70ffa37fb061fa737ec/gramps_webapi/dbmanager.py#L43

**Comment by DavidMStraub** [comment]
> I tried password: Optional[str] = None as your comment suggested but that didn't change any test case failures, instead I found that setting the type to be either str or None makes the test cases pass:

Which failures? `str or None` is not a valid type hint. I think it will just evaluate as `str` (since `str` is not falsey the part after `or` is never evaluated.

> Are you asking me to add another method for gramps-webapi to read POSTGRES_PASSWORD (through some other configuration)?

Yes, it should just be a normal configuration parameter that can be optionally set from the environment, as I suggested in the previous PR:

```python
app.config["POSTGRES_PASSWORD"] = app.config["POSTGRES_PASSWORD"] or os.getenv("POSTGRES_PASSWORD")`
```
and then you can just use `app.config["POSTGRES_PASSWORD"]` in the instantiation.

**Comment by Rahel-A** [comment]
> > I tried password: Optional[str] = None as your comment suggested but that didn't change any test case failures, instead I found that setting the type to be either str or None makes the test cases pass:
> 
> Which failures? `str or None` is not a valid type hint. I think it will just evaluate as `str` (since `str` is not falsey the part after `or` is never evaluated.
> 
> > Are you asking me to add another method for gramps-webapi to read POSTGRES_PASSWORD (through some other configuration)?
> 
> Yes, it should just be a normal configuration parameter that can be optionally set from the environment, as I suggested in the previous PR:
> 
> ```python
> app.config["POSTGRES_PASSWORD"] = app.config["POSTGRES_PASSWORD"] or os.getenv("POSTGRES_PASSWORD")`
> ```
> 
> and then you can just use `app.config["POSTGRES_PASSWORD"]` in the instantiation.

OK, sorry for the confusion earlier. I've addressed your comments and the test cases pass now.

**Comment by DavidMStraub** [comment]
Thanks!

**Comment by DavidMStraub** [comment]
Oops, I forgot that this won't work until https://github.com/gramps-project/addons-source/pull/523 is merged. Anyway I think it's fine if we don't release the next version before.

**Comment by Rahel-A** [comment]
> Oops, I forgot that this won't work until [gramps-project/addons-source#523](https://github.com/gramps-project/addons-source/pull/523) is merged. Anyway I think it's fine if we don't release the next version before.

There's also the other workaround available until that gets merged, you can set the number of GUNICORN workers to 1.

**Pull request merged**
