### PR TITLE
Limit relation search depth, estimate death date if needed

### PR DESCRIPTION
**Pull request by cdhorn**
@DavidMStraub I hope this addresses #164 and #165  I choose to use `probably_alive` for the calculation of the death date to bound with if no event indicating death is identifiable for the anchor person. For the relationship calculator the depth is set to `max(ancestors, offspring) + 1`

### CODE REVIEW

**Comment by cdhorn** [comment]
This second commit fixes more issues.  The age of the person the event is for is now included in the person profile, and if the timeline is not anchored to a person also returned in that age field as well. I think that age field was not returning the age of the anchor person for their own events, if so that is fixed too. Age calculation is now done in profile assembly as well.

Are you also playing with a family timeline view?

Let me know what else you find that I overlooked or need to fix.

**Comment by DavidMStraub** [comment]
Great! I can confirm that it fixes both issues!

I haven't started with the family timeline view, but I suppose it will not be difficult to do it starting from the person one.

**Comment by DavidMStraub** [comment]
There is just one more small issue I noticed: for one person (where the person events are not ordered chronologically for some reason), the christening/baptism events is 3 days after the birth and Gramps correctly shows the age as "3 days". However, in the timeline for some reason the birth shows an age of "3 days" and the baptism and age of "0 days". The events are correctly ordered chronologically though. Do you know what might be going on?

**Comment by DavidMStraub** [comment]
Sorry, noticed another issue: for a person without a birth event (birthdate is unknown), I get

```
gramps_webapi/api/resources/timeline.py", line 461, in profile
    self.birth_dates[self.anchor_person.handle], event[0].date
KeyError
```

**Comment by cdhorn** [comment]
Don't be sorry, I'm sorry you're debugging so much! Please check if this fixes those two if you don't mind.

**Comment by DavidMStraub** [comment]
Yes, both issues are fixed for me, thanks! Ready to merge?

**Comment by cdhorn** [comment]
Excellent!  Sure whenever you are ready.

**Pull request merged**
