### PR TITLE
Initialize mimetypes first (For #168)

### PR DESCRIPTION
**Pull request by cdhorn**
@DavidMStraub let's see if adding mimetypes.init() fixes it on your end.

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Now I get this:

```
  File "gramps_webapi/api/resources/reports.py", line 118, in run_report
    "Can not find {} in mimetypes.types_map" % file_type
TypeError: not all arguments converted during string formatting
```

I think you should use `" ... {} ... ".format(...)`.

**Comment by cdhorn** [comment]
Yeah but if it hit that the mimetypes.init() clearly didn't resolve the issue on your system...  

Is this running in the container or externally or both?

**Comment by DavidMStraub** [comment]
This was just running directly on my machine, no container.

**Comment by cdhorn** [comment]
This shouldn't be related, but did it leave any work files in the Gramps temp directory?  Can you check and let me know and if so if they are .dot or .dot.gv as perhaps that was a bug later fixed and I need to special case it. That thought just occurred to me. 

I think I added REPORT_PATH and EXPORT_PATH to override that behaviour BTW.

I think you run Ubuntu right?  Focal?  Can you shoot me level and apt list --installed output and the package list from the virtual environment you're running it in?  I want to try to reproduce it.  I know we could hard code and be done with it but I'd much rather figure out why now...

**Comment by DavidMStraub** [comment]
I looked into it a bit ... apparently `mimetypes` just looks into `/etc/mime.types` on my system, which does not contain an entry for Graphviz. `xdg-mime` apparently uses data in `/usr/share/mime`, which *does* include info about Graphviz.

In the end it really seems the easiest (and must robust) way would be to hardcode all types needed for Gramps. Sorry for originally suggesting `mimetypes`, it is less useful than I thought ...

**Comment by cdhorn** [comment]
No need to apologize, it seems we both learned something new.  Learn something new every day!

**Pull request merged**
